// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import ()

type Product struct {
	ID     int32
	Name   string
	UserID int32
}

type User struct {
	ID   int32
	Name string
}
